# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'benchmark'

Specialty.destroy_all
Specialty.create(
  [
    { name: 'Acompanhamento Terapêutico' },
    { name: 'Adoção de Filhos' },
    { name: 'Adolescência' },
    { name: 'Agorafobia' },
    { name: 'Anorexia Nervosa' },
    { name: 'Ansiedade' },
    { name: 'Aprendizagem' },
    { name: 'Asperger' },
    { name: 'Assessoramento acadêmico' },
    { name: 'Autismo' },
    { name: 'Avaliação Neuropsicológica' },
    { name: 'Baby Blues' },
    { name: 'Borderline' },
    { name: 'Bulimia Nervosa' },
    { name: 'Câncer' },
    { name: 'Casais' },
    { name: 'Casamento' },
    { name: 'Cirurgia Bariátrica' },
    { name: 'Cleptomania' },
    { name: 'Coaching' },
    { name: 'Compulsão Alimentar' },
    { name: 'Compulsões' },
    { name: 'Conflitos Amorosos' },
    { name: 'Conflitos Familiares' },
    { name: 'Conflitos Legais' },
    { name: 'Cuidados Paliativos' },
    { name: 'Dependência Jogos' },
    { name: 'Dependência Química' },
    { name: 'Depressão' },
    { name: 'Depressão Pós-parto' },
    { name: 'Desenvolvimento Pessoal' },
    { name: 'Dificuldade de Aprendizagem' },
    { name: 'Discalculia' },
    { name: 'Disfunções Sexuais' },
    { name: 'Dislexia' },
    { name: 'Distimia' },
    { name: 'Distúrbios Alimentares' },
    { name: 'Doenças Crônicas' },
    { name: 'Dor' },
    { name: 'Drogas' },
    { name: 'Educação Escolar' },
    { name: 'Emagrecimento' },
    { name: 'Encoprese' },
    { name: 'Entrevistas psicológicas' },
    { name: 'Enurese' },
    { name: 'Esquizofrenia' },
    { name: 'Estresse' },
    { name: 'Estresse pós-traumático' },
    { name: 'Família' },
    { name: 'Fobia Social' },
    { name: 'Fobias' },
    { name: 'Hiperatividade' },
    { name: 'Hipocondria' },
    { name: 'Idosos Terceira Idade' },
    { name: 'Infância' },
    { name: 'Libras - Língua Brasileira de Sinais' },
    { name: 'Ludoterapia' },
    { name: 'Medos' },
    { name: 'Morte e Luto' },
    { name: 'Neuropsicologia' },
    { name: 'Neuropsicologia do Idoso' },
    { name: 'Neuropsicologia Infantil' },
    { name: 'Obesidade' },
    { name: 'Orientação de educadores' },
    { name: 'Orientação de Pais' },
    { name: 'Orientação para Cirurgia Bariátrica' },
    { name: 'Orientação Profissional' },
    { name: 'Orientação Psicológica' },
    { name: 'Orientação Psicopedagógica' },
    { name: 'Orientação Vocacional' },
    { name: 'Pessoas com Deficiência - PCD' },
    { name: 'Piromania' },
    { name: 'Planejamento Psicopedagógico' },
    { name: 'Preparação para Aposentadoria' },
    { name: 'Problemas de Aprendizagem' },
    { name: 'Psicologia Infantil' },
    { name: 'Reabilitação Cognitiva' },
    { name: 'Reabilitação Neuropsicológica' },
    { name: 'Relacionamentos afetivos' },
    { name: 'Saúde do trabalhador' },
    { name: 'Saúde Mental' },
    { name: 'Sexologia' },
    { name: 'Sexualidade' },
    { name: 'Síndrome de Burnout' },
    { name: 'Síndrome do Pânico' },
    { name: 'Suicídio' },
    { name: 'Supervisão Clínica em Psicologia' },
    { name: 'Tanatologia' },
    { name: 'TDA e TDAH' },
    { name: 'TDAH' },
    { name: 'Terapia Sexual' },
    { name: 'Testes Psicológicos' },
    { name: 'TOC - Transtorno Obsessivo' },
    { name: 'Transição de Carreiras' },
    { name: 'Transtorno Bipolar' },
    { name: 'Transtorno da Personalidade Borderline' },
    { name: 'Transtorno da Personalidade Histriônica' },
    { name: 'Transtorno da Personalidade Narcisista' },
    { name: 'Transtorno de Acumulação' },
    { name: 'Transtorno de Ansiedade Generalizada (TAG)' },
    { name: 'Transtorno de Compulsão Alimentar' },
    { name: 'Transtornos Alimentares' },
    { name: 'Transtornos da Personalidade' },
    { name: 'Transtornos de Humor' },
    { name: 'Transtornos Depressivos e de Humor' },
    { name: 'Transtornos do Neurodesenvolvimento' },
    { name: 'Tratamento Memória' },
    { name: 'Treinamento Empresarial' },
    { name: 'Tricotilomania' },
    { name: 'Violência Doméstica' },
    { name: 'Violência Sexual' }
  ]
)

Approach.destroy_all
Approach.create(
  [
    { name: 'Análise Bioenergética' },
    { name: 'Análise do Comportamento | Behaviorismo' },
    { name: 'Análise Transacional' },
    { name: 'Coaching de Carreira' },
    { name: 'Coaching de Emagrecimento' },
    { name: 'Coaching de Negócios' },
    { name: 'Coaching de Vida' },
    { name: 'Coaching Executivo' },
    { name: 'Constelações Sistêmicas Familiares' },
    { name: 'Corporal | Reichiana' },
    { name: 'Daseinsanalyse' },
    { name: 'Fenomenologia Existencial' },
    { name: 'Gestalt Terapia' },
    { name: 'Hipnoterapia' },
    { name: 'Humanista' },
    { name: 'Humanista | Abordagem centrada na pessoa' },
    { name: 'Junguianos' },
    { name: 'Ludoterapia' },
    { name: 'Mindfulness' },
    { name: 'Neuropsicologia' },
    { name: 'Psicanálise | Bion' },
    { name: 'Psicanálise | Freud' },
    { name: 'Psicanálise | Klein' },
    { name: 'Psicanálise | Lacan' },
    { name: 'Psicanálise | Winnicott' },
    { name: 'Psicanalistas' },
    { name: 'Psicodrama' },
    { name: 'Psicologia Analítica | Jung' },
    { name: 'Psicologia Clínica' },
    { name: 'Psicologia do Esporte' },
    { name: 'Psicopedagogia' },
    { name: 'Psicossomática Psicanalítica' },
    { name: 'Psicoterapia Breve' },
    { name: 'Teoria do Apego' },
    { name: 'Terapia Cognitiva Comportamental Dialética' },
    { name: 'Terapia Cognitivo Comportamental' },
    { name: 'Terapia EMDR' },
    { name: 'Terapia Familiar' },
    { name: 'Transpessoal' }
  ]
)